language: ruby
rvm:
- 2.0.0
notifications:
  email:
  - tech@amicushq.com
  campfire:
    rooms:
      secure: BxJjTeW5CXdTpYUbISJM9HlP+gj2SejivBt246kbBDAcjfxuk+DnWNgW2C+oGEdCYOom+PLlYuHVfhCe3KQnToxkAk1eNmjCC3rMNS4FD1SzhzIdoY2XVZx9kWkv8u4V5+cCqxwn7CyaS8d7aQMFP4gBCziVu4Pezt6QgACZGNc=
branches:
  only:
  - master
  - production
before_install:
  - wget http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
  - sudo dpkg -i influxdb_latest_amd64.deb
  - influxdb
script:
  - bundle exec rspec
